apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: golang-manager
  name: golang-manager
  namespace: golang-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: golang-manager
  template:
    metadata:
      labels:
        control-plane: golang-manager
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}        
        command:
        - /app/manager
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: golang-manager
      terminationGracePeriodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
