name: "Golang Build & Publish"

on:
  workflow_dispatch:

jobs:
  ra_version:
    permissions:
      packages: write
      actions: read
      contents: write

    name: "Generate versions from common workflow"
    # uses: "Rockwell-Automation-FTDS/configuration-cd/.github/workflows/raver.yml@1.3.3"
    uses: "./.github/workflows/raver.yml"

  tag-project:
    name: Tag the project
    needs: [ra_version]
    runs-on: ubuntu-latest

    permissions:
      packages: write
      actions: read
      contents: write          # for actions/checkout to fetch code
      pull-requests: write
      security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results

    steps:
      - name: Create tag and push
        # if:  github.ref_name == 'main'
        run: |
          echo "Pushing new version ${{ needs.ra_version.outputs.version }} "
          git tag ${{ needs.ra_version.outputs.version }} && git push --tags
          
